# Generated by Django 3.2.4 on 2021-08-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=2)),
                ('subject', models.TextField()),
                ('day', models.CharField(max_length=2)),
            ],
        ),
    ]
